<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateCountries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->bigInteger('country_code')->default(0)->unique()->index();
            $table->char('iso', 2)->index()->unique();
            $table->string('name', 80);
            $table->string('default_name', 80);
            $table->char('iso3', 3)->nullable();
            $table->smallinteger('num_code')->nullable();
            $table->integer('phone_code');
            $table->timestamps();
        });

        DB::table('countries')->delete();

        $countries = array(
            array('id' => '1', 'country_code' => crc32(1), 'iso' => 'AF', 'name' => 'AFGHANISTAN', 'default_name' => 'Afghanistan', 'iso3' => 'AFG', 'num_code' => '4', 'phone_code' => '93'),
            array('id' => '2', 'country_code' => crc32(2), 'iso' => 'AL', 'name' => 'ALBANIA', 'default_name' => 'Albania', 'iso3' => 'ALB', 'num_code' => '8', 'phone_code' => '355'),
            array('id' => '3', 'country_code' => crc32(3), 'iso' => 'DZ', 'name' => 'ALGERIA', 'default_name' => 'Algeria', 'iso3' => 'DZA', 'num_code' => '12', 'phone_code' => '213'),
            array('id' => '4', 'country_code' => crc32(4), 'iso' => 'AS', 'name' => 'AMERICAN SAMOA', 'default_name' => 'American Samoa', 'iso3' => 'ASM', 'num_code' => '16', 'phone_code' => '1684'),
            array('id' => '5', 'country_code' => crc32(5), 'iso' => 'AD', 'name' => 'ANDORRA', 'default_name' => 'Andorra', 'iso3' => 'AND', 'num_code' => '20', 'phone_code' => '376'),
            array('id' => '6', 'country_code' => crc32(6), 'iso' => 'AO', 'name' => 'ANGOLA', 'default_name' => 'Angola', 'iso3' => 'AGO', 'num_code' => '24', 'phone_code' => '244'),
            array('id' => '7', 'country_code' => crc32(7), 'iso' => 'AI', 'name' => 'ANGUILLA', 'default_name' => 'Anguilla', 'iso3' => 'AIA', 'num_code' => '660', 'phone_code' => '1264'),
            array('id' => '8', 'country_code' => crc32(8), 'iso' => 'AQ', 'name' => 'ANTARCTICA', 'default_name' => 'Antarctica', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '0'),
            array('id' => '9', 'country_code' => crc32(9), 'iso' => 'AG', 'name' => 'ANTIGUA AND BARBUDA', 'default_name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'num_code' => '28', 'phone_code' => '1268'),
            array('id' => '10', 'country_code' => crc32(10), 'iso' => 'AR', 'name' => 'ARGENTINA', 'default_name' => 'Argentina', 'iso3' => 'ARG', 'num_code' => '32', 'phone_code' => '54'),
            array('id' => '11', 'country_code' => crc32(11), 'iso' => 'AM', 'name' => 'ARMENIA', 'default_name' => 'Armenia', 'iso3' => 'ARM', 'num_code' => '51', 'phone_code' => '374'),
            array('id' => '12', 'country_code' => crc32(12), 'iso' => 'AW', 'name' => 'ARUBA', 'default_name' => 'Aruba', 'iso3' => 'ABW', 'num_code' => '533', 'phone_code' => '297'),
            array('id' => '13', 'country_code' => crc32(13), 'iso' => 'AU', 'name' => 'AUSTRALIA', 'default_name' => 'Australia', 'iso3' => 'AUS', 'num_code' => '36', 'phone_code' => '61'),
            array('id' => '14', 'country_code' => crc32(14), 'iso' => 'AT', 'name' => 'AUSTRIA', 'default_name' => 'Austria', 'iso3' => 'AUT', 'num_code' => '40', 'phone_code' => '43'),
            array('id' => '15', 'country_code' => crc32(15), 'iso' => 'AZ', 'name' => 'AZERBAIJAN', 'default_name' => 'Azerbaijan', 'iso3' => 'AZE', 'num_code' => '31', 'phone_code' => '994'),
            array('id' => '16', 'country_code' => crc32(16), 'iso' => 'BS', 'name' => 'BAHAMAS', 'default_name' => 'Bahamas', 'iso3' => 'BHS', 'num_code' => '44', 'phone_code' => '1242'),
            array('id' => '17', 'country_code' => crc32(17), 'iso' => 'BH', 'name' => 'BAHRAIN', 'default_name' => 'Bahrain', 'iso3' => 'BHR', 'num_code' => '48', 'phone_code' => '973'),
            array('id' => '18', 'country_code' => crc32(18), 'iso' => 'BD', 'name' => 'BANGLADESH', 'default_name' => 'Bangladesh', 'iso3' => 'BGD', 'num_code' => '50', 'phone_code' => '880'),
            array('id' => '19', 'country_code' => crc32(19), 'iso' => 'BB', 'name' => 'BARBADOS', 'default_name' => 'Barbados', 'iso3' => 'BRB', 'num_code' => '52', 'phone_code' => '1246'),
            array('id' => '20', 'country_code' => crc32(20), 'iso' => 'BY', 'name' => 'BELARUS', 'default_name' => 'Belarus', 'iso3' => 'BLR', 'num_code' => '112', 'phone_code' => '375'),
            array('id' => '21', 'country_code' => crc32(21), 'iso' => 'BE', 'name' => 'BELGIUM', 'default_name' => 'Belgium', 'iso3' => 'BEL', 'num_code' => '56', 'phone_code' => '32'),
            array('id' => '22', 'country_code' => crc32(22), 'iso' => 'BZ', 'name' => 'BELIZE', 'default_name' => 'Belize', 'iso3' => 'BLZ', 'num_code' => '84', 'phone_code' => '501'),
            array('id' => '23', 'country_code' => crc32(23), 'iso' => 'BJ', 'name' => 'BENIN', 'default_name' => 'Benin', 'iso3' => 'BEN', 'num_code' => '204', 'phone_code' => '229'),
            array('id' => '24', 'country_code' => crc32(24), 'iso' => 'BM', 'name' => 'BERMUDA', 'default_name' => 'Bermuda', 'iso3' => 'BMU', 'num_code' => '60', 'phone_code' => '1441'),
            array('id' => '25', 'country_code' => crc32(25), 'iso' => 'BT', 'name' => 'BHUTAN', 'default_name' => 'Bhutan', 'iso3' => 'BTN', 'num_code' => '64', 'phone_code' => '975'),
            array('id' => '26', 'country_code' => crc32(26), 'iso' => 'BO', 'name' => 'BOLIVIA', 'default_name' => 'Bolivia', 'iso3' => 'BOL', 'num_code' => '68', 'phone_code' => '591'),
            array('id' => '27', 'country_code' => crc32(27), 'iso' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA', 'default_name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'num_code' => '70', 'phone_code' => '387'),
            array('id' => '28', 'country_code' => crc32(28), 'iso' => 'BW', 'name' => 'BOTSWANA', 'default_name' => 'Botswana', 'iso3' => 'BWA', 'num_code' => '72', 'phone_code' => '267'),
            array('id' => '29', 'country_code' => crc32(29), 'iso' => 'BV', 'name' => 'BOUVET ISLAND', 'default_name' => 'Bouvet Island', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '0'),
            array('id' => '30', 'country_code' => crc32(30), 'iso' => 'BR', 'name' => 'BRAZIL', 'default_name' => 'Brazil', 'iso3' => 'BRA', 'num_code' => '76', 'phone_code' => '55'),
            array('id' => '31', 'country_code' => crc32(31), 'iso' => 'IO', 'name' => 'BRITISH INDIAN OCEAN TERRITORY', 'default_name' => 'British Indian Ocean Territory', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '246'),
            array('id' => '32', 'country_code' => crc32(32), 'iso' => 'BN', 'name' => 'BRUNEI DARUSSALAM', 'default_name' => 'Brunei Darussalam', 'iso3' => 'BRN', 'num_code' => '96', 'phone_code' => '673'),
            array('id' => '33', 'country_code' => crc32(33), 'iso' => 'BG', 'name' => 'BULGARIA', 'default_name' => 'Bulgaria', 'iso3' => 'BGR', 'num_code' => '100', 'phone_code' => '359'),
            array('id' => '34', 'country_code' => crc32(34), 'iso' => 'BF', 'name' => 'BURKINA FASO', 'default_name' => 'Burkina Faso', 'iso3' => 'BFA', 'num_code' => '854', 'phone_code' => '226'),
            array('id' => '35', 'country_code' => crc32(35), 'iso' => 'BI', 'name' => 'BURUNDI', 'default_name' => 'Burundi', 'iso3' => 'BDI', 'num_code' => '108', 'phone_code' => '257'),
            array('id' => '36', 'country_code' => crc32(36), 'iso' => 'KH', 'name' => 'CAMBODIA', 'default_name' => 'Cambodia', 'iso3' => 'KHM', 'num_code' => '116', 'phone_code' => '855'),
            array('id' => '37', 'country_code' => crc32(37), 'iso' => 'CM', 'name' => 'CAMEROON', 'default_name' => 'Cameroon', 'iso3' => 'CMR', 'num_code' => '120', 'phone_code' => '237'),
            array('id' => '38', 'country_code' => crc32(38), 'iso' => 'CA', 'name' => 'CANADA', 'default_name' => 'Canada', 'iso3' => 'CAN', 'num_code' => '124', 'phone_code' => '1'),
            array('id' => '39', 'country_code' => crc32(39), 'iso' => 'CV', 'name' => 'CAPE VERDE', 'default_name' => 'Cape Verde', 'iso3' => 'CPV', 'num_code' => '132', 'phone_code' => '238'),
            array('id' => '40', 'country_code' => crc32(40), 'iso' => 'KY', 'name' => 'CAYMAN ISLANDS', 'default_name' => 'Cayman Islands', 'iso3' => 'CYM', 'num_code' => '136', 'phone_code' => '1345'),
            array('id' => '41', 'country_code' => crc32(41), 'iso' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'default_name' => 'Central African Republic', 'iso3' => 'CAF', 'num_code' => '140', 'phone_code' => '236'),
            array('id' => '42', 'country_code' => crc32(42), 'iso' => 'TD', 'name' => 'CHAD', 'default_name' => 'Chad', 'iso3' => 'TCD', 'num_code' => '148', 'phone_code' => '235'),
            array('id' => '43', 'country_code' => crc32(43), 'iso' => 'CL', 'name' => 'CHILE', 'default_name' => 'Chile', 'iso3' => 'CHL', 'num_code' => '152', 'phone_code' => '56'),
            array('id' => '44', 'country_code' => crc32(44), 'iso' => 'CN', 'name' => 'CHINA', 'default_name' => 'China', 'iso3' => 'CHN', 'num_code' => '156', 'phone_code' => '86'),
            array('id' => '45', 'country_code' => crc32(45), 'iso' => 'CX', 'name' => 'CHRISTMAS ISLAND', 'default_name' => 'Christmas Island', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '61'),
            array('id' => '46', 'country_code' => crc32(46), 'iso' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS', 'default_name' => 'Cocos (Keeling) Islands', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '672'),
            array('id' => '47', 'country_code' => crc32(47), 'iso' => 'CO', 'name' => 'COLOMBIA', 'default_name' => 'Colombia', 'iso3' => 'COL', 'num_code' => '170', 'phone_code' => '57'),
            array('id' => '48', 'country_code' => crc32(48), 'iso' => 'KM', 'name' => 'COMOROS', 'default_name' => 'Comoros', 'iso3' => 'COM', 'num_code' => '174', 'phone_code' => '269'),
            array('id' => '49', 'country_code' => crc32(49), 'iso' => 'CG', 'name' => 'CONGO', 'default_name' => 'Congo', 'iso3' => 'COG', 'num_code' => '178', 'phone_code' => '242'),
            array('id' => '50', 'country_code' => crc32(50), 'iso' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'default_name' => 'Congo, the Democratic Republic of the', 'iso3' => 'COD', 'num_code' => '180', 'phone_code' => '242'),
            array('id' => '51', 'country_code' => crc32(51), 'iso' => 'CK', 'name' => 'COOK ISLANDS', 'default_name' => 'Cook Islands', 'iso3' => 'COK', 'num_code' => '184', 'phone_code' => '682'),
            array('id' => '52', 'country_code' => crc32(52), 'iso' => 'CR', 'name' => 'COSTA RICA', 'default_name' => 'Costa Rica', 'iso3' => 'CRI', 'num_code' => '188', 'phone_code' => '506'),
            array('id' => '53', 'country_code' => crc32(53), 'iso' => 'CI', 'name' => 'COTE D\'IVOIRE', 'default_name' => 'Cote D\'Ivoire', 'iso3' => 'CIV', 'num_code' => '384', 'phone_code' => '225'),
            array('id' => '54', 'country_code' => crc32(54), 'iso' => 'HR', 'name' => 'CROATIA', 'default_name' => 'Croatia', 'iso3' => 'HRV', 'num_code' => '191', 'phone_code' => '385'),
            array('id' => '55', 'country_code' => crc32(55), 'iso' => 'CU', 'name' => 'CUBA', 'default_name' => 'Cuba', 'iso3' => 'CUB', 'num_code' => '192', 'phone_code' => '53'),
            array('id' => '56', 'country_code' => crc32(56), 'iso' => 'CY', 'name' => 'CYPRUS', 'default_name' => 'Cyprus', 'iso3' => 'CYP', 'num_code' => '196', 'phone_code' => '357'),
            array('id' => '57', 'country_code' => crc32(57), 'iso' => 'CZ', 'name' => 'CZECH REPUBLIC', 'default_name' => 'Czech Republic', 'iso3' => 'CZE', 'num_code' => '203', 'phone_code' => '420'),
            array('id' => '58', 'country_code' => crc32(58), 'iso' => 'DK', 'name' => 'DENMARK', 'default_name' => 'Denmark', 'iso3' => 'DNK', 'num_code' => '208', 'phone_code' => '45'),
            array('id' => '59', 'country_code' => crc32(59), 'iso' => 'DJ', 'name' => 'DJIBOUTI', 'default_name' => 'Djibouti', 'iso3' => 'DJI', 'num_code' => '262', 'phone_code' => '253'),
            array('id' => '60', 'country_code' => crc32(60), 'iso' => 'DM', 'name' => 'DOMINICA', 'default_name' => 'Dominica', 'iso3' => 'DMA', 'num_code' => '212', 'phone_code' => '1767'),
            array('id' => '61', 'country_code' => crc32(61), 'iso' => 'DO', 'name' => 'DOMINICAN REPUBLIC', 'default_name' => 'Dominican Republic', 'iso3' => 'DOM', 'num_code' => '214', 'phone_code' => '1809'),
            array('id' => '62', 'country_code' => crc32(62), 'iso' => 'EC', 'name' => 'ECUADOR', 'default_name' => 'Ecuador', 'iso3' => 'ECU', 'num_code' => '218', 'phone_code' => '593'),
            array('id' => '63', 'country_code' => crc32(63), 'iso' => 'EG', 'name' => 'EGYPT', 'default_name' => 'Egypt', 'iso3' => 'EGY', 'num_code' => '818', 'phone_code' => '20'),
            array('id' => '64', 'country_code' => crc32(64), 'iso' => 'SV', 'name' => 'EL SALVADOR', 'default_name' => 'El Salvador', 'iso3' => 'SLV', 'num_code' => '222', 'phone_code' => '503'),
            array('id' => '65', 'country_code' => crc32(65), 'iso' => 'GQ', 'name' => 'EQUATORIAL GUINEA', 'default_name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'num_code' => '226', 'phone_code' => '240'),
            array('id' => '66', 'country_code' => crc32(66), 'iso' => 'ER', 'name' => 'ERITREA', 'default_name' => 'Eritrea', 'iso3' => 'ERI', 'num_code' => '232', 'phone_code' => '291'),
            array('id' => '67', 'country_code' => crc32(67), 'iso' => 'EE', 'name' => 'ESTONIA', 'default_name' => 'Estonia', 'iso3' => 'EST', 'num_code' => '233', 'phone_code' => '372'),
            array('id' => '68', 'country_code' => crc32(68), 'iso' => 'ET', 'name' => 'ETHIOPIA', 'default_name' => 'Ethiopia', 'iso3' => 'ETH', 'num_code' => '231', 'phone_code' => '251'),
            array('id' => '69', 'country_code' => crc32(69), 'iso' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)', 'default_name' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'num_code' => '238', 'phone_code' => '500'),
            array('id' => '70', 'country_code' => crc32(70), 'iso' => 'FO', 'name' => 'FAROE ISLANDS', 'default_name' => 'Faroe Islands', 'iso3' => 'FRO', 'num_code' => '234', 'phone_code' => '298'),
            array('id' => '71', 'country_code' => crc32(71), 'iso' => 'FJ', 'name' => 'FIJI', 'default_name' => 'Fiji', 'iso3' => 'FJI', 'num_code' => '242', 'phone_code' => '679'),
            array('id' => '72', 'country_code' => crc32(72), 'iso' => 'FI', 'name' => 'FINLAND', 'default_name' => 'Finland', 'iso3' => 'FIN', 'num_code' => '246', 'phone_code' => '358'),
            array('id' => '73', 'country_code' => crc32(73), 'iso' => 'FR', 'name' => 'FRANCE', 'default_name' => 'France', 'iso3' => 'FRA', 'num_code' => '250', 'phone_code' => '33'),
            array('id' => '74', 'country_code' => crc32(74), 'iso' => 'GF', 'name' => 'FRENCH GUIANA', 'default_name' => 'French Guiana', 'iso3' => 'GUF', 'num_code' => '254', 'phone_code' => '594'),
            array('id' => '75', 'country_code' => crc32(75), 'iso' => 'PF', 'name' => 'FRENCH POLYNESIA', 'default_name' => 'French Polynesia', 'iso3' => 'PYF', 'num_code' => '258', 'phone_code' => '689'),
            array('id' => '76', 'country_code' => crc32(76), 'iso' => 'TF', 'name' => 'FRENCH SOUTHERN TERRITORIES', 'default_name' => 'French Southern Territories', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '0'),
            array('id' => '77', 'country_code' => crc32(77), 'iso' => 'GA', 'name' => 'GABON', 'default_name' => 'Gabon', 'iso3' => 'GAB', 'num_code' => '266', 'phone_code' => '241'),
            array('id' => '78', 'country_code' => crc32(78), 'iso' => 'GM', 'name' => 'GAMBIA', 'default_name' => 'Gambia', 'iso3' => 'GMB', 'num_code' => '270', 'phone_code' => '220'),
            array('id' => '79', 'country_code' => crc32(79), 'iso' => 'GE', 'name' => 'GEORGIA', 'default_name' => 'Georgia', 'iso3' => 'GEO', 'num_code' => '268', 'phone_code' => '995'),
            array('id' => '80', 'country_code' => crc32(80), 'iso' => 'DE', 'name' => 'GERMANY', 'default_name' => 'Germany', 'iso3' => 'DEU', 'num_code' => '276', 'phone_code' => '49'),
            array('id' => '81', 'country_code' => crc32(81), 'iso' => 'GH', 'name' => 'GHANA', 'default_name' => 'Ghana', 'iso3' => 'GHA', 'num_code' => '288', 'phone_code' => '233'),
            array('id' => '82', 'country_code' => crc32(82), 'iso' => 'GI', 'name' => 'GIBRALTAR', 'default_name' => 'Gibraltar', 'iso3' => 'GIB', 'num_code' => '292', 'phone_code' => '350'),
            array('id' => '83', 'country_code' => crc32(83), 'iso' => 'GR', 'name' => 'GREECE', 'default_name' => 'Greece', 'iso3' => 'GRC', 'num_code' => '300', 'phone_code' => '30'),
            array('id' => '84', 'country_code' => crc32(84), 'iso' => 'GL', 'name' => 'GREENLAND', 'default_name' => 'Greenland', 'iso3' => 'GRL', 'num_code' => '304', 'phone_code' => '299'),
            array('id' => '85', 'country_code' => crc32(85), 'iso' => 'GD', 'name' => 'GRENADA', 'default_name' => 'Grenada', 'iso3' => 'GRD', 'num_code' => '308', 'phone_code' => '1473'),
            array('id' => '86', 'country_code' => crc32(86), 'iso' => 'GP', 'name' => 'GUADELOUPE', 'default_name' => 'Guadeloupe', 'iso3' => 'GLP', 'num_code' => '312', 'phone_code' => '590'),
            array('id' => '87', 'country_code' => crc32(87), 'iso' => 'GU', 'name' => 'GUAM', 'default_name' => 'Guam', 'iso3' => 'GUM', 'num_code' => '316', 'phone_code' => '1671'),
            array('id' => '88', 'country_code' => crc32(88), 'iso' => 'GT', 'name' => 'GUATEMALA', 'default_name' => 'Guatemala', 'iso3' => 'GTM', 'num_code' => '320', 'phone_code' => '502'),
            array('id' => '89', 'country_code' => crc32(89), 'iso' => 'GN', 'name' => 'GUINEA', 'default_name' => 'Guinea', 'iso3' => 'GIN', 'num_code' => '324', 'phone_code' => '224'),
            array('id' => '90', 'country_code' => crc32(90), 'iso' => 'GW', 'name' => 'GUINEA-BISSAU', 'default_name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'num_code' => '624', 'phone_code' => '245'),
            array('id' => '91', 'country_code' => crc32(91), 'iso' => 'GY', 'name' => 'GUYANA', 'default_name' => 'Guyana', 'iso3' => 'GUY', 'num_code' => '328', 'phone_code' => '592'),
            array('id' => '92', 'country_code' => crc32(92), 'iso' => 'HT', 'name' => 'HAITI', 'default_name' => 'Haiti', 'iso3' => 'HTI', 'num_code' => '332', 'phone_code' => '509'),
            array('id' => '93', 'country_code' => crc32(93), 'iso' => 'HM', 'name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'default_name' => 'Heard Island and Mcdonald Islands', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '0'),
            array('id' => '94', 'country_code' => crc32(94), 'iso' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)', 'default_name' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'num_code' => '336', 'phone_code' => '39'),
            array('id' => '95', 'country_code' => crc32(95), 'iso' => 'HN', 'name' => 'HONDURAS', 'default_name' => 'Honduras', 'iso3' => 'HND', 'num_code' => '340', 'phone_code' => '504'),
            array('id' => '96', 'country_code' => crc32(96), 'iso' => 'HK', 'name' => 'HONG KONG', 'default_name' => 'Hong Kong', 'iso3' => 'HKG', 'num_code' => '344', 'phone_code' => '852'),
            array('id' => '97', 'country_code' => crc32(97), 'iso' => 'HU', 'name' => 'HUNGARY', 'default_name' => 'Hungary', 'iso3' => 'HUN', 'num_code' => '348', 'phone_code' => '36'),
            array('id' => '98', 'country_code' => crc32(98), 'iso' => 'IS', 'name' => 'ICELAND', 'default_name' => 'Iceland', 'iso3' => 'ISL', 'num_code' => '352', 'phone_code' => '354'),
            array('id' => '99', 'country_code' => crc32(99), 'iso' => 'IN', 'name' => 'INDIA', 'default_name' => 'India', 'iso3' => 'IND', 'num_code' => '356', 'phone_code' => '91'),
            array('id' => '100', 'country_code' => crc32(100), 'iso' => 'ID', 'name' => 'INDONESIA', 'default_name' => 'Indonesia', 'iso3' => 'IDN', 'num_code' => '360', 'phone_code' => '62'),
            array('id' => '101', 'country_code' => crc32(101), 'iso' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF', 'default_name' => 'Iran, Islamic Republic of', 'iso3' => 'IRN', 'num_code' => '364', 'phone_code' => '98'),
            array('id' => '102', 'country_code' => crc32(102), 'iso' => 'IQ', 'name' => 'IRAQ', 'default_name' => 'Iraq', 'iso3' => 'IRQ', 'num_code' => '368', 'phone_code' => '964'),
            array('id' => '103', 'country_code' => crc32(103), 'iso' => 'IE', 'name' => 'IRELAND', 'default_name' => 'Ireland', 'iso3' => 'IRL', 'num_code' => '372', 'phone_code' => '353'),
            array('id' => '104', 'country_code' => crc32(104), 'iso' => 'IL', 'name' => 'ISRAEL', 'default_name' => 'Israel', 'iso3' => 'ISR', 'num_code' => '376', 'phone_code' => '972'),
            array('id' => '105', 'country_code' => crc32(105), 'iso' => 'IT', 'name' => 'ITALY', 'default_name' => 'Italy', 'iso3' => 'ITA', 'num_code' => '380', 'phone_code' => '39'),
            array('id' => '106', 'country_code' => crc32(106), 'iso' => 'JM', 'name' => 'JAMAICA', 'default_name' => 'Jamaica', 'iso3' => 'JAM', 'num_code' => '388', 'phone_code' => '1876'),
            array('id' => '107', 'country_code' => crc32(107), 'iso' => 'JP', 'name' => 'JAPAN', 'default_name' => 'Japan', 'iso3' => 'JPN', 'num_code' => '392', 'phone_code' => '81'),
            array('id' => '108', 'country_code' => crc32(108), 'iso' => 'JO', 'name' => 'JORDAN', 'default_name' => 'Jordan', 'iso3' => 'JOR', 'num_code' => '400', 'phone_code' => '962'),
            array('id' => '109', 'country_code' => crc32(109), 'iso' => 'KZ', 'name' => 'KAZAKHSTAN', 'default_name' => 'Kazakhstan', 'iso3' => 'KAZ', 'num_code' => '398', 'phone_code' => '7'),
            array('id' => '110', 'country_code' => crc32(110), 'iso' => 'KE', 'name' => 'KENYA', 'default_name' => 'Kenya', 'iso3' => 'KEN', 'num_code' => '404', 'phone_code' => '254'),
            array('id' => '111', 'country_code' => crc32(111), 'iso' => 'KI', 'name' => 'KIRIBATI', 'default_name' => 'Kiribati', 'iso3' => 'KIR', 'num_code' => '296', 'phone_code' => '686'),
            array('id' => '112', 'country_code' => crc32(112), 'iso' => 'KP', 'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'default_name' => 'Korea, Democratic People\'s Republic of', 'iso3' => 'PRK', 'num_code' => '408', 'phone_code' => '850'),
            array('id' => '113', 'country_code' => crc32(113), 'iso' => 'KR', 'name' => 'KOREA, REPUBLIC OF', 'default_name' => 'Korea, Republic of', 'iso3' => 'KOR', 'num_code' => '410', 'phone_code' => '82'),
            array('id' => '114', 'country_code' => crc32(114), 'iso' => 'KW', 'name' => 'KUWAIT', 'default_name' => 'Kuwait', 'iso3' => 'KWT', 'num_code' => '414', 'phone_code' => '965'),
            array('id' => '115', 'country_code' => crc32(115), 'iso' => 'KG', 'name' => 'KYRGYZSTAN', 'default_name' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'num_code' => '417', 'phone_code' => '996'),
            array('id' => '116', 'country_code' => crc32(116), 'iso' => 'LA', 'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'default_name' => 'Lao People\'s Democratic Republic', 'iso3' => 'LAO', 'num_code' => '418', 'phone_code' => '856'),
            array('id' => '117', 'country_code' => crc32(117), 'iso' => 'LV', 'name' => 'LATVIA', 'default_name' => 'Latvia', 'iso3' => 'LVA', 'num_code' => '428', 'phone_code' => '371'),
            array('id' => '118', 'country_code' => crc32(118), 'iso' => 'LB', 'name' => 'LEBANON', 'default_name' => 'Lebanon', 'iso3' => 'LBN', 'num_code' => '422', 'phone_code' => '961'),
            array('id' => '119', 'country_code' => crc32(119), 'iso' => 'LS', 'name' => 'LESOTHO', 'default_name' => 'Lesotho', 'iso3' => 'LSO', 'num_code' => '426', 'phone_code' => '266'),
            array('id' => '120', 'country_code' => crc32(120), 'iso' => 'LR', 'name' => 'LIBERIA', 'default_name' => 'Liberia', 'iso3' => 'LBR', 'num_code' => '430', 'phone_code' => '231'),
            array('id' => '121', 'country_code' => crc32(121), 'iso' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA', 'default_name' => 'Libyan Arab Jamahiriya', 'iso3' => 'LBY', 'num_code' => '434', 'phone_code' => '218'),
            array('id' => '122', 'country_code' => crc32(122), 'iso' => 'LI', 'name' => 'LIECHTENSTEIN', 'default_name' => 'Liechtenstein', 'iso3' => 'LIE', 'num_code' => '438', 'phone_code' => '423'),
            array('id' => '123', 'country_code' => crc32(123), 'iso' => 'LT', 'name' => 'LITHUANIA', 'default_name' => 'Lithuania', 'iso3' => 'LTU', 'num_code' => '440', 'phone_code' => '370'),
            array('id' => '124', 'country_code' => crc32(124), 'iso' => 'LU', 'name' => 'LUXEMBOURG', 'default_name' => 'Luxembourg', 'iso3' => 'LUX', 'num_code' => '442', 'phone_code' => '352'),
            array('id' => '125', 'country_code' => crc32(125), 'iso' => 'MO', 'name' => 'MACAO', 'default_name' => 'Macao', 'iso3' => 'MAC', 'num_code' => '446', 'phone_code' => '853'),
            array('id' => '126', 'country_code' => crc32(126), 'iso' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'default_name' => 'Macedonia, the Former Yugoslav Republic of', 'iso3' => 'MKD', 'num_code' => '807', 'phone_code' => '389'),
            array('id' => '127', 'country_code' => crc32(127), 'iso' => 'MG', 'name' => 'MADAGASCAR', 'default_name' => 'Madagascar', 'iso3' => 'MDG', 'num_code' => '450', 'phone_code' => '261'),
            array('id' => '128', 'country_code' => crc32(128), 'iso' => 'MW', 'name' => 'MALAWI', 'default_name' => 'Malawi', 'iso3' => 'MWI', 'num_code' => '454', 'phone_code' => '265'),
            array('id' => '129', 'country_code' => crc32(129), 'iso' => 'MY', 'name' => 'MALAYSIA', 'default_name' => 'Malaysia', 'iso3' => 'MYS', 'num_code' => '458', 'phone_code' => '60'),
            array('id' => '130', 'country_code' => crc32(130), 'iso' => 'MV', 'name' => 'MALDIVES', 'default_name' => 'Maldives', 'iso3' => 'MDV', 'num_code' => '462', 'phone_code' => '960'),
            array('id' => '131', 'country_code' => crc32(131), 'iso' => 'ML', 'name' => 'MALI', 'default_name' => 'Mali', 'iso3' => 'MLI', 'num_code' => '466', 'phone_code' => '223'),
            array('id' => '132', 'country_code' => crc32(132), 'iso' => 'MT', 'name' => 'MALTA', 'default_name' => 'Malta', 'iso3' => 'MLT', 'num_code' => '470', 'phone_code' => '356'),
            array('id' => '133', 'country_code' => crc32(133), 'iso' => 'MH', 'name' => 'MARSHALL ISLANDS', 'default_name' => 'Marshall Islands', 'iso3' => 'MHL', 'num_code' => '584', 'phone_code' => '692'),
            array('id' => '134', 'country_code' => crc32(134), 'iso' => 'MQ', 'name' => 'MARTINIQUE', 'default_name' => 'Martinique', 'iso3' => 'MTQ', 'num_code' => '474', 'phone_code' => '596'),
            array('id' => '135', 'country_code' => crc32(135), 'iso' => 'MR', 'name' => 'MAURITANIA', 'default_name' => 'Mauritania', 'iso3' => 'MRT', 'num_code' => '478', 'phone_code' => '222'),
            array('id' => '136', 'country_code' => crc32(136), 'iso' => 'MU', 'name' => 'MAURITIUS', 'default_name' => 'Mauritius', 'iso3' => 'MUS', 'num_code' => '480', 'phone_code' => '230'),
            array('id' => '137', 'country_code' => crc32(137), 'iso' => 'YT', 'name' => 'MAYOTTE', 'default_name' => 'Mayotte', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '269'),
            array('id' => '138', 'country_code' => crc32(138), 'iso' => 'MX', 'name' => 'MEXICO', 'default_name' => 'Mexico', 'iso3' => 'MEX', 'num_code' => '484', 'phone_code' => '52'),
            array('id' => '139', 'country_code' => crc32(139), 'iso' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'default_name' => 'Micronesia, Federated States of', 'iso3' => 'FSM', 'num_code' => '583', 'phone_code' => '691'),
            array('id' => '140', 'country_code' => crc32(140), 'iso' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF', 'default_name' => 'Moldova, Republic of', 'iso3' => 'MDA', 'num_code' => '498', 'phone_code' => '373'),
            array('id' => '141', 'country_code' => crc32(141), 'iso' => 'MC', 'name' => 'MONACO', 'default_name' => 'Monaco', 'iso3' => 'MCO', 'num_code' => '492', 'phone_code' => '377'),
            array('id' => '142', 'country_code' => crc32(142), 'iso' => 'MN', 'name' => 'MONGOLIA', 'default_name' => 'Mongolia', 'iso3' => 'MNG', 'num_code' => '496', 'phone_code' => '976'),
            array('id' => '143', 'country_code' => crc32(143), 'iso' => 'MS', 'name' => 'MONTSERRAT', 'default_name' => 'Montserrat', 'iso3' => 'MSR', 'num_code' => '500', 'phone_code' => '1664'),
            array('id' => '144', 'country_code' => crc32(144), 'iso' => 'MA', 'name' => 'MOROCCO', 'default_name' => 'Morocco', 'iso3' => 'MAR', 'num_code' => '504', 'phone_code' => '212'),
            array('id' => '145', 'country_code' => crc32(145), 'iso' => 'MZ', 'name' => 'MOZAMBIQUE', 'default_name' => 'Mozambique', 'iso3' => 'MOZ', 'num_code' => '508', 'phone_code' => '258'),
            array('id' => '146', 'country_code' => crc32(146), 'iso' => 'MM', 'name' => 'MYANMAR', 'default_name' => 'Myanmar', 'iso3' => 'MMR', 'num_code' => '104', 'phone_code' => '95'),
            array('id' => '147', 'country_code' => crc32(147), 'iso' => 'NA', 'name' => 'NAMIBIA', 'default_name' => 'Namibia', 'iso3' => 'NAM', 'num_code' => '516', 'phone_code' => '264'),
            array('id' => '148', 'country_code' => crc32(148), 'iso' => 'NR', 'name' => 'NAURU', 'default_name' => 'Nauru', 'iso3' => 'NRU', 'num_code' => '520', 'phone_code' => '674'),
            array('id' => '149', 'country_code' => crc32(149), 'iso' => 'NP', 'name' => 'NEPAL', 'default_name' => 'Nepal', 'iso3' => 'NPL', 'num_code' => '524', 'phone_code' => '977'),
            array('id' => '150', 'country_code' => crc32(150), 'iso' => 'NL', 'name' => 'NETHERLANDS', 'default_name' => 'Netherlands', 'iso3' => 'NLD', 'num_code' => '528', 'phone_code' => '31'),
            array('id' => '151', 'country_code' => crc32(151), 'iso' => 'AN', 'name' => 'NETHERLANDS ANTILLES', 'default_name' => 'Netherlands Antilles', 'iso3' => 'ANT', 'num_code' => '530', 'phone_code' => '599'),
            array('id' => '152', 'country_code' => crc32(152), 'iso' => 'NC', 'name' => 'NEW CALEDONIA', 'default_name' => 'New Caledonia', 'iso3' => 'NCL', 'num_code' => '540', 'phone_code' => '687'),
            array('id' => '153', 'country_code' => crc32(153), 'iso' => 'NZ', 'name' => 'NEW ZEALAND', 'default_name' => 'New Zealand', 'iso3' => 'NZL', 'num_code' => '554', 'phone_code' => '64'),
            array('id' => '154', 'country_code' => crc32(154), 'iso' => 'NI', 'name' => 'NICARAGUA', 'default_name' => 'Nicaragua', 'iso3' => 'NIC', 'num_code' => '558', 'phone_code' => '505'),
            array('id' => '155', 'country_code' => crc32(155), 'iso' => 'NE', 'name' => 'NIGER', 'default_name' => 'Niger', 'iso3' => 'NER', 'num_code' => '562', 'phone_code' => '227'),
            array('id' => '156', 'country_code' => crc32(156), 'iso' => 'NG', 'name' => 'NIGERIA', 'default_name' => 'Nigeria', 'iso3' => 'NGA', 'num_code' => '566', 'phone_code' => '234'),
            array('id' => '157', 'country_code' => crc32(157), 'iso' => 'NU', 'name' => 'NIUE', 'default_name' => 'Niue', 'iso3' => 'NIU', 'num_code' => '570', 'phone_code' => '683'),
            array('id' => '158', 'country_code' => crc32(158), 'iso' => 'NF', 'name' => 'NORFOLK ISLAND', 'default_name' => 'Norfolk Island', 'iso3' => 'NFK', 'num_code' => '574', 'phone_code' => '672'),
            array('id' => '159', 'country_code' => crc32(159), 'iso' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS', 'default_name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'num_code' => '580', 'phone_code' => '1670'),
            array('id' => '160', 'country_code' => crc32(160), 'iso' => 'NO', 'name' => 'NORWAY', 'default_name' => 'Norway', 'iso3' => 'NOR', 'num_code' => '578', 'phone_code' => '47'),
            array('id' => '161', 'country_code' => crc32(161), 'iso' => 'OM', 'name' => 'OMAN', 'default_name' => 'Oman', 'iso3' => 'OMN', 'num_code' => '512', 'phone_code' => '968'),
            array('id' => '162', 'country_code' => crc32(162), 'iso' => 'PK', 'name' => 'PAKISTAN', 'default_name' => 'Pakistan', 'iso3' => 'PAK', 'num_code' => '586', 'phone_code' => '92'),
            array('id' => '163', 'country_code' => crc32(163), 'iso' => 'PW', 'name' => 'PALAU', 'default_name' => 'Palau', 'iso3' => 'PLW', 'num_code' => '585', 'phone_code' => '680'),
            array('id' => '164', 'country_code' => crc32(164), 'iso' => 'PS', 'name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'default_name' => 'Palestinian Territory, Occupied', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '970'),
            array('id' => '165', 'country_code' => crc32(165), 'iso' => 'PA', 'name' => 'PANAMA', 'default_name' => 'Panama', 'iso3' => 'PAN', 'num_code' => '591', 'phone_code' => '507'),
            array('id' => '166', 'country_code' => crc32(166), 'iso' => 'PG', 'name' => 'PAPUA NEW GUINEA', 'default_name' => 'Papua New Guinea', 'iso3' => 'PNG', 'num_code' => '598', 'phone_code' => '675'),
            array('id' => '167', 'country_code' => crc32(167), 'iso' => 'PY', 'name' => 'PARAGUAY', 'default_name' => 'Paraguay', 'iso3' => 'PRY', 'num_code' => '600', 'phone_code' => '595'),
            array('id' => '168', 'country_code' => crc32(168), 'iso' => 'PE', 'name' => 'PERU', 'default_name' => 'Peru', 'iso3' => 'PER', 'num_code' => '604', 'phone_code' => '51'),
            array('id' => '169', 'country_code' => crc32(169), 'iso' => 'PH', 'name' => 'PHILIPPINES', 'default_name' => 'Philippines', 'iso3' => 'PHL', 'num_code' => '608', 'phone_code' => '63'),
            array('id' => '170', 'country_code' => crc32(170), 'iso' => 'PN', 'name' => 'PITCAIRN', 'default_name' => 'Pitcairn', 'iso3' => 'PCN', 'num_code' => '612', 'phone_code' => '0'),
            array('id' => '171', 'country_code' => crc32(171), 'iso' => 'PL', 'name' => 'POLAND', 'default_name' => 'Poland', 'iso3' => 'POL', 'num_code' => '616', 'phone_code' => '48'),
            array('id' => '172', 'country_code' => crc32(172), 'iso' => 'PT', 'name' => 'PORTUGAL', 'default_name' => 'Portugal', 'iso3' => 'PRT', 'num_code' => '620', 'phone_code' => '351'),
            array('id' => '173', 'country_code' => crc32(173), 'iso' => 'PR', 'name' => 'PUERTO RICO', 'default_name' => 'Puerto Rico', 'iso3' => 'PRI', 'num_code' => '630', 'phone_code' => '1787'),
            array('id' => '174', 'country_code' => crc32(174), 'iso' => 'QA', 'name' => 'QATAR', 'default_name' => 'Qatar', 'iso3' => 'QAT', 'num_code' => '634', 'phone_code' => '974'),
            array('id' => '175', 'country_code' => crc32(175), 'iso' => 'RE', 'name' => 'REUNION', 'default_name' => 'Reunion', 'iso3' => 'REU', 'num_code' => '638', 'phone_code' => '262'),
            array('id' => '176', 'country_code' => crc32(176), 'iso' => 'RO', 'name' => 'ROMANIA', 'default_name' => 'Romania', 'iso3' => 'ROM', 'num_code' => '642', 'phone_code' => '40'),
            array('id' => '177', 'country_code' => crc32(177), 'iso' => 'RU', 'name' => 'RUSSIAN FEDERATION', 'default_name' => 'Russian Federation', 'iso3' => 'RUS', 'num_code' => '643', 'phone_code' => '70'),
            array('id' => '178', 'country_code' => crc32(178), 'iso' => 'RW', 'name' => 'RWANDA', 'default_name' => 'Rwanda', 'iso3' => 'RWA', 'num_code' => '646', 'phone_code' => '250'),
            array('id' => '179', 'country_code' => crc32(179), 'iso' => 'SH', 'name' => 'SAINT HELENA', 'default_name' => 'Saint Helena', 'iso3' => 'SHN', 'num_code' => '654', 'phone_code' => '290'),
            array('id' => '180', 'country_code' => crc32(180), 'iso' => 'KN', 'name' => 'SAINT KITTS AND NEVIS', 'default_name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'num_code' => '659', 'phone_code' => '1869'),
            array('id' => '181', 'country_code' => crc32(181), 'iso' => 'LC', 'name' => 'SAINT LUCIA', 'default_name' => 'Saint Lucia', 'iso3' => 'LCA', 'num_code' => '662', 'phone_code' => '1758'),
            array('id' => '182', 'country_code' => crc32(182), 'iso' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON', 'default_name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'num_code' => '666', 'phone_code' => '508'),
            array('id' => '183', 'country_code' => crc32(183), 'iso' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'default_name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'num_code' => '670', 'phone_code' => '1784'),
            array('id' => '184', 'country_code' => crc32(184), 'iso' => 'WS', 'name' => 'SAMOA', 'default_name' => 'Samoa', 'iso3' => 'WSM', 'num_code' => '882', 'phone_code' => '684'),
            array('id' => '185', 'country_code' => crc32(185), 'iso' => 'SM', 'name' => 'SAN MARINO', 'default_name' => 'San Marino', 'iso3' => 'SMR', 'num_code' => '674', 'phone_code' => '378'),
            array('id' => '186', 'country_code' => crc32(186), 'iso' => 'ST', 'name' => 'SAO TOME AND PRINCIPE', 'default_name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'num_code' => '678', 'phone_code' => '239'),
            array('id' => '187', 'country_code' => crc32(187), 'iso' => 'SA', 'name' => 'SAUDI ARABIA', 'default_name' => 'Saudi Arabia', 'iso3' => 'SAU', 'num_code' => '682', 'phone_code' => '966'),
            array('id' => '188', 'country_code' => crc32(188), 'iso' => 'SN', 'name' => 'SENEGAL', 'default_name' => 'Senegal', 'iso3' => 'SEN', 'num_code' => '686', 'phone_code' => '221'),
            array('id' => '189', 'country_code' => crc32(189), 'iso' => 'CS', 'name' => 'SERBIA AND MONTENEGRO', 'default_name' => 'Serbia and Montenegro', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '381'),
            array('id' => '190', 'country_code' => crc32(190), 'iso' => 'SC', 'name' => 'SEYCHELLES', 'default_name' => 'Seychelles', 'iso3' => 'SYC', 'num_code' => '690', 'phone_code' => '248'),
            array('id' => '191', 'country_code' => crc32(191), 'iso' => 'SL', 'name' => 'SIERRA LEONE', 'default_name' => 'Sierra Leone', 'iso3' => 'SLE', 'num_code' => '694', 'phone_code' => '232'),
            array('id' => '192', 'country_code' => crc32(192), 'iso' => 'SG', 'name' => 'SINGAPORE', 'default_name' => 'Singapore', 'iso3' => 'SGP', 'num_code' => '702', 'phone_code' => '65'),
            array('id' => '193', 'country_code' => crc32(193), 'iso' => 'SK', 'name' => 'SLOVAKIA', 'default_name' => 'Slovakia', 'iso3' => 'SVK', 'num_code' => '703', 'phone_code' => '421'),
            array('id' => '194', 'country_code' => crc32(194), 'iso' => 'SI', 'name' => 'SLOVENIA', 'default_name' => 'Slovenia', 'iso3' => 'SVN', 'num_code' => '705', 'phone_code' => '386'),
            array('id' => '195', 'country_code' => crc32(195), 'iso' => 'SB', 'name' => 'SOLOMON ISLANDS', 'default_name' => 'Solomon Islands', 'iso3' => 'SLB', 'num_code' => '90', 'phone_code' => '677'),
            array('id' => '196', 'country_code' => crc32(196), 'iso' => 'SO', 'name' => 'SOMALIA', 'default_name' => 'Somalia', 'iso3' => 'SOM', 'num_code' => '706', 'phone_code' => '252'),
            array('id' => '197', 'country_code' => crc32(197), 'iso' => 'ZA', 'name' => 'SOUTH AFRICA', 'default_name' => 'South Africa', 'iso3' => 'ZAF', 'num_code' => '710', 'phone_code' => '27'),
            array('id' => '198', 'country_code' => crc32(198), 'iso' => 'GS', 'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'default_name' => 'South Georgia and the South Sandwich Islands', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '0'),
            array('id' => '199', 'country_code' => crc32(199), 'iso' => 'ES', 'name' => 'SPAIN', 'default_name' => 'Spain', 'iso3' => 'ESP', 'num_code' => '724', 'phone_code' => '34'),
            array('id' => '200', 'country_code' => crc32(200), 'iso' => 'LK', 'name' => 'SRI LANKA', 'default_name' => 'Sri Lanka', 'iso3' => 'LKA', 'num_code' => '144', 'phone_code' => '94'),
            array('id' => '201', 'country_code' => crc32(201), 'iso' => 'SD', 'name' => 'SUDAN', 'default_name' => 'Sudan', 'iso3' => 'SDN', 'num_code' => '736', 'phone_code' => '249'),
            array('id' => '202', 'country_code' => crc32(202), 'iso' => 'SR', 'name' => 'SURINAME', 'default_name' => 'Suriname', 'iso3' => 'SUR', 'num_code' => '740', 'phone_code' => '597'),
            array('id' => '203', 'country_code' => crc32(203), 'iso' => 'SJ', 'name' => 'SVALBARD AND JAN MAYEN', 'default_name' => 'Svalbard and Jan Mayen', 'iso3' => 'SJM', 'num_code' => '744', 'phone_code' => '47'),
            array('id' => '204', 'country_code' => crc32(204), 'iso' => 'SZ', 'name' => 'SWAZILAND', 'default_name' => 'Swaziland', 'iso3' => 'SWZ', 'num_code' => '748', 'phone_code' => '268'),
            array('id' => '205', 'country_code' => crc32(205), 'iso' => 'SE', 'name' => 'SWEDEN', 'default_name' => 'Sweden', 'iso3' => 'SWE', 'num_code' => '752', 'phone_code' => '46'),
            array('id' => '206', 'country_code' => crc32(206), 'iso' => 'CH', 'name' => 'SWITZERLAND', 'default_name' => 'Switzerland', 'iso3' => 'CHE', 'num_code' => '756', 'phone_code' => '41'),
            array('id' => '207', 'country_code' => crc32(207), 'iso' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC', 'default_name' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'num_code' => '760', 'phone_code' => '963'),
            array('id' => '208', 'country_code' => crc32(208), 'iso' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA', 'default_name' => 'Taiwan, Province of China', 'iso3' => 'TWN', 'num_code' => '158', 'phone_code' => '886'),
            array('id' => '209', 'country_code' => crc32(209), 'iso' => 'TJ', 'name' => 'TAJIKISTAN', 'default_name' => 'Tajikistan', 'iso3' => 'TJK', 'num_code' => '762', 'phone_code' => '992'),
            array('id' => '210', 'country_code' => crc32(210), 'iso' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'default_name' => 'Tanzania, United Republic of', 'iso3' => 'TZA', 'num_code' => '834', 'phone_code' => '255'),
            array('id' => '211', 'country_code' => crc32(211), 'iso' => 'TH', 'name' => 'THAILAND', 'default_name' => 'Thailand', 'iso3' => 'THA', 'num_code' => '764', 'phone_code' => '66'),
            array('id' => '212', 'country_code' => crc32(212), 'iso' => 'TL', 'name' => 'TIMOR-LESTE', 'default_name' => 'Timor-Leste', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '670'),
            array('id' => '213', 'country_code' => crc32(213), 'iso' => 'TG', 'name' => 'TOGO', 'default_name' => 'Togo', 'iso3' => 'TGO', 'num_code' => '768', 'phone_code' => '228'),
            array('id' => '214', 'country_code' => crc32(214), 'iso' => 'TK', 'name' => 'TOKELAU', 'default_name' => 'Tokelau', 'iso3' => 'TKL', 'num_code' => '772', 'phone_code' => '690'),
            array('id' => '215', 'country_code' => crc32(215), 'iso' => 'TO', 'name' => 'TONGA', 'default_name' => 'Tonga', 'iso3' => 'TON', 'num_code' => '776', 'phone_code' => '676'),
            array('id' => '216', 'country_code' => crc32(216), 'iso' => 'TT', 'name' => 'TRINIDAD AND TOBAGO', 'default_name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'num_code' => '780', 'phone_code' => '1868'),
            array('id' => '217', 'country_code' => crc32(217), 'iso' => 'TN', 'name' => 'TUNISIA', 'default_name' => 'Tunisia', 'iso3' => 'TUN', 'num_code' => '788', 'phone_code' => '216'),
            array('id' => '218', 'country_code' => crc32(218), 'iso' => 'TR', 'name' => 'TURKEY', 'default_name' => 'Turkey', 'iso3' => 'TUR', 'num_code' => '792', 'phone_code' => '90'),
            array('id' => '219', 'country_code' => crc32(219), 'iso' => 'TM', 'name' => 'TURKMENISTAN', 'default_name' => 'Turkmenistan', 'iso3' => 'TKM', 'num_code' => '795', 'phone_code' => '7370'),
            array('id' => '220', 'country_code' => crc32(220), 'iso' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS', 'default_name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'num_code' => '796', 'phone_code' => '1649'),
            array('id' => '221', 'country_code' => crc32(221), 'iso' => 'TV', 'name' => 'TUVALU', 'default_name' => 'Tuvalu', 'iso3' => 'TUV', 'num_code' => '798', 'phone_code' => '688'),
            array('id' => '222', 'country_code' => crc32(222), 'iso' => 'UG', 'name' => 'UGANDA', 'default_name' => 'Uganda', 'iso3' => 'UGA', 'num_code' => '800', 'phone_code' => '256'),
            array('id' => '223', 'country_code' => crc32(223), 'iso' => 'UA', 'name' => 'UKRAINE', 'default_name' => 'Ukraine', 'iso3' => 'UKR', 'num_code' => '804', 'phone_code' => '380'),
            array('id' => '224', 'country_code' => crc32(224), 'iso' => 'AE', 'name' => 'UNITED ARAB EMIRATES', 'default_name' => 'United Arab Emirates', 'iso3' => 'ARE', 'num_code' => '784', 'phone_code' => '971'),
            array('id' => '225', 'country_code' => crc32(225), 'iso' => 'GB', 'name' => 'UNITED KINGDOM', 'default_name' => 'United Kingdom', 'iso3' => 'GBR', 'num_code' => '826', 'phone_code' => '44'),
            array('id' => '226', 'country_code' => crc32(226), 'iso' => 'US', 'name' => 'UNITED STATES', 'default_name' => 'United States', 'iso3' => 'USA', 'num_code' => '840', 'phone_code' => '1'),
            array('id' => '227', 'country_code' => crc32(227), 'iso' => 'UM', 'name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'default_name' => 'United States Minor Outlying Islands', 'iso3' => NULL, 'num_code' => NULL, 'phone_code' => '1'),
            array('id' => '228', 'country_code' => crc32(228), 'iso' => 'UY', 'name' => 'URUGUAY', 'default_name' => 'Uruguay', 'iso3' => 'URY', 'num_code' => '858', 'phone_code' => '598'),
            array('id' => '229', 'country_code' => crc32(229), 'iso' => 'UZ', 'name' => 'UZBEKISTAN', 'default_name' => 'Uzbekistan', 'iso3' => 'UZB', 'num_code' => '860', 'phone_code' => '998'),
            array('id' => '230', 'country_code' => crc32(230), 'iso' => 'VU', 'name' => 'VANUATU', 'default_name' => 'Vanuatu', 'iso3' => 'VUT', 'num_code' => '548', 'phone_code' => '678'),
            array('id' => '231', 'country_code' => crc32(231), 'iso' => 'VE', 'name' => 'VENEZUELA', 'default_name' => 'Venezuela', 'iso3' => 'VEN', 'num_code' => '862', 'phone_code' => '58'),
            array('id' => '232', 'country_code' => crc32(232), 'iso' => 'VN', 'name' => 'VIET NAM', 'default_name' => 'Viet Nam', 'iso3' => 'VNM', 'num_code' => '704', 'phone_code' => '84'),
            array('id' => '233', 'country_code' => crc32(233), 'iso' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH', 'default_name' => 'Virgin Islands, British', 'iso3' => 'VGB', 'num_code' => '92', 'phone_code' => '1284'),
            array('id' => '234', 'country_code' => crc32(234), 'iso' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.', 'default_name' => 'Virgin Islands, U.s.', 'iso3' => 'VIR', 'num_code' => '850', 'phone_code' => '1340'),
            array('id' => '235', 'country_code' => crc32(235), 'iso' => 'WF', 'name' => 'WALLIS AND FUTUNA', 'default_name' => 'Wallis and Futuna', 'iso3' => 'WLF', 'num_code' => '876', 'phone_code' => '681'),
            array('id' => '236', 'country_code' => crc32(236), 'iso' => 'EH', 'name' => 'WESTERN SAHARA', 'default_name' => 'Western Sahara', 'iso3' => 'ESH', 'num_code' => '732', 'phone_code' => '212'),
            array('id' => '237', 'country_code' => crc32(237), 'iso' => 'YE', 'name' => 'YEMEN', 'default_name' => 'Yemen', 'iso3' => 'YEM', 'num_code' => '887', 'phone_code' => '967'),
            array('id' => '238', 'country_code' => crc32(238), 'iso' => 'ZM', 'name' => 'ZAMBIA', 'default_name' => 'Zambia', 'iso3' => 'ZMB', 'num_code' => '894', 'phone_code' => '260'),
            array('id' => '239', 'country_code' => crc32(239), 'iso' => 'ZW', 'name' => 'ZIMBABWE', 'default_name' => 'Zimbabwe', 'iso3' => 'ZWE', 'num_code' => '716', 'phone_code' => '263'),
            array('id' => '240', 'country_code' => crc32(240), 'iso' => 'RS', 'name' => 'SERBIA', 'default_name' => 'Serbia', 'iso3' => 'SRB', 'num_code' => '688', 'phone_code' => '381'),
            array('id' => '241', 'country_code' => crc32(241), 'iso' => 'AP', 'name' => 'ASIA PACIFIC REGION', 'default_name' => 'Asia / Pacific Region', 'iso3' => '0', 'num_code' => '0', 'phone_code' => '0'),
            array('id' => '242', 'country_code' => crc32(242), 'iso' => 'ME', 'name' => 'MONTENEGRO', 'default_name' => 'Montenegro', 'iso3' => 'MNE', 'num_code' => '499', 'phone_code' => '382'),
            array('id' => '243', 'country_code' => crc32(243), 'iso' => 'AX', 'name' => 'ALAND ISLANDS', 'default_name' => 'Aland Islands', 'iso3' => 'ALA', 'num_code' => '248', 'phone_code' => '358'),
            array('id' => '244', 'country_code' => crc32(244), 'iso' => 'BQ', 'name' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'default_name' => 'Bonaire, Sint Eustatius and Saba', 'iso3' => 'BES', 'num_code' => '535', 'phone_code' => '599'),
            array('id' => '245', 'country_code' => crc32(245), 'iso' => 'CW', 'name' => 'CURACAO', 'default_name' => 'Curacao', 'iso3' => 'CUW', 'num_code' => '531', 'phone_code' => '599'),
            array('id' => '246', 'country_code' => crc32(246), 'iso' => 'GG', 'name' => 'GUERNSEY', 'default_name' => 'Guernsey', 'iso3' => 'GGY', 'num_code' => '831', 'phone_code' => '44'),
            array('id' => '247', 'country_code' => crc32(247), 'iso' => 'IM', 'name' => 'ISLE OF MAN', 'default_name' => 'Isle of Man', 'iso3' => 'IMN', 'num_code' => '833', 'phone_code' => '44'),
            array('id' => '248', 'country_code' => crc32(248), 'iso' => 'JE', 'name' => 'JERSEY', 'default_name' => 'Jersey', 'iso3' => 'JEY', 'num_code' => '832', 'phone_code' => '44'),
            array('id' => '249', 'country_code' => crc32(249), 'iso' => 'XK', 'name' => 'KOSOVO', 'default_name' => 'Kosovo', 'iso3' => '---', 'num_code' => '0', 'phone_code' => '381'),
            array('id' => '250', 'country_code' => crc32(250), 'iso' => 'BL', 'name' => 'SAINT BARTHELEMY', 'default_name' => 'Saint Barthelemy', 'iso3' => 'BLM', 'num_code' => '652', 'phone_code' => '590'),
            array('id' => '251', 'country_code' => crc32(251), 'iso' => 'MF', 'name' => 'SAINT MARTIN', 'default_name' => 'Saint Martin', 'iso3' => 'MAF', 'num_code' => '663', 'phone_code' => '590'),
            array('id' => '252', 'country_code' => crc32(252), 'iso' => 'SX', 'name' => 'SINT MAARTEN', 'default_name' => 'Sint Maarten', 'iso3' => 'SXM', 'num_code' => '534', 'phone_code' => '1'),
            array('id' => '253', 'country_code' => crc32(253), 'iso' => 'SS', 'name' => 'SOUTH SUDAN', 'default_name' => 'South Sudan', 'iso3' => 'SSD', 'num_code' => '728', 'phone_code' => '211')
        );

        DB::table('countries')->insert($countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
